# Generated by Django 6.0.4 on 2026-05-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Draw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField(unique=True)),
                ("win_num1", models.IntegerField()),
                ("win_num2", models.IntegerField()),
                ("win_num3", models.IntegerField()),
                ("win_num4", models.IntegerField()),
                ("win_num5", models.IntegerField()),
                ("win_num6", models.IntegerField()),
                ("draw_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num1", models.IntegerField()),
                ("num2", models.IntegerField()),
                ("num3", models.IntegerField()),
                ("num4", models.IntegerField()),
                ("num5", models.IntegerField()),
                ("num6", models.IntegerField()),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
