# Generated by Django 6.0.4 on 2026-05-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WinningNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField(default=1)),
                ("num1", models.IntegerField()),
                ("num2", models.IntegerField()),
                ("num3", models.IntegerField()),
                ("num4", models.IntegerField()),
                ("num5", models.IntegerField()),
                ("num6", models.IntegerField()),
                ("bonus", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="purchase_date",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="draw",
            name="bonus_num",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="draw",
            name="draw_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
