#ai로 프로그래밍
version: '3'

services:

  web:
    build: .
    container_name: lotto_web
    working_dir: /app/mysite
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    depends_on:
      - db

    environment:
      - DB_NAME=lotto_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:17

    container_name: lotto_db

    restart: always

    environment:
      POSTGRES_DB: lotto_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
